{
 "title": "Houmlab Golden Signals",
 "description": "Golden Signals Visualization 4 Houmlab URL Shortener",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 200 Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{outcome=\"SUCCESS\", status=\"200\", uri!=\"/actuator/prometheus\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current HTTP 200 Traffic",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{status=\"200\", uri!=\"/actuator/prometheus\"}[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirection Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{outcome=\"REDIRECTION\", status=\"302\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Redirection Traffic",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{outcome=\"REDIRECTION\", status=\"302\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non Successful ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status!=\"200\", status!=\"302\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads (Saturation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  }
 ]
}